### ISSUE TITLE
为什么huggingface的模型404了

### ISSUE THREAD

**Issue by Cuihongsen** [codefuse-ai/FasterTransformer4CodeFuse#1]
昨天看到了开源了CodeFuse的报道，今天去huggingface上发现并没有模型文件，报道中的相关模型链接跳转是404的。

Yesterday I saw the news about CodeFuse being open-sourced, but today when I went to huggingface, I found that there were no model files available. The link to the related models mentioned in the article leads to a 404 error page.

**Comment by sfss5362** [comment]
https://github.com/codefuse-ai/.github/blob/main/profile/README_CN.md

https://modelscope.cn/models/ss41979310/CodeFuse-13B/files
https://modelscope.cn/models/ss41979310/CodeFuse-CodeLlama-34B/files

**Comment by ss41979310** [comment]
Due to internet connection issue, the uploaded file on huggingface were corrupted. The file were re-uploaded on that Sunday. Now, model files are held on both huggingface and modelscope. 

HF:
https://huggingface.co/codefuse-ai/CodeFuse-CodeLlama-34B
https://huggingface.co/codefuse-ai/CodeFuse-13B

MS:
https://modelscope.cn/models/codefuse-ai/CodeFuse-CodeLlama-34B/summary
https://modelscope.cn/models/codefuse-ai/CodeFuse-13B/summary
